
spring:
  application:
    name: cloud-consul-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
      ##设置不需要注册到 consul 中
        register: false
server:
  port: 8503