#server.port=8988
#spring.zipkin.base-url=http://localhost:9411
#spring.application.name=service-hi
server:
  port: 8989
spring:
  zipkin:
    base-url: http://localhost:9411
  application:
    name: service-hello
